// Walet transaction
export const LOAD_WALLET_TRANSACTION_HISTORY = "wallets/LOAD_WALLET_TRANSACTION_HISTORY";
export const LOAD_WALLET_TRANSACTION_LIST = "wallets/LOAD_WALLET_TRANSACTION_LIST";
export const LOAD_WALLET_TRANSACTION_DETAIL = "wallets/LOAD_WALLET_TRANSACTION_DETAIL";
export const LOAD_WALLET_TRANSACTION_TYPE = "wallets/LOAD_WALLET_TRANSACTION_TYPE";
export const LOAD_WALLET_TRANSACTION_DIRECT_LIST = "wallets/LOAD_WALLET_TRANSACTION_DIRECT_LIST";

// Sale transaction
export const LOAD_SALE_WALLET_LIST = "wallets/LOAD_SALE_WALLET_LIST";
export const LOAD_SALE_TRANSACTION_LIST = "wallets/LOAD_SALE_TRANSACTION_LIST";
// wallet list
export const LOAD_WALLET_LIST = "wallets/LOAD_WALLET_LIST";
export const BLOCK_WALLET = "wallets/BLOCK_WALLET";

export const DELETE_WALLET = "wallets/DELETE_WALLET";
export const SHOW_WALLET = "wallets/SHOW_WALLET";
export const APPROVE_TRANSACTION = "wallets/APPROVE_TRANSACTION";
export const REJECT_TRANSACTION = "wallets/REJECT_TRANSACTION";
export const RECHARGE_MONEY = "wallets/RECHARGE_MONEY";
export const WITHDRAWAL_MONEY = "wallets/WITHDRAWAL_MONEY";
export const UPDATE_TRANSACTION_DIRECT = "wallets/UPDATE_TRANSACTION_DIRECT";